# Generated by Django 5.1.2 on 2024-10-25 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='user',
        ),
    ]
