# Generated by Django 5.1.2 on 2024-10-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_carmodel_user'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='cars',
            field=models.ManyToManyField(related_name='users', to='cars.carmodel'),
        ),
    ]
